# Include packages that pull up and auto-init the link layer.
# NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
# Specify the mandatory networking modules
USEMODULE += gnrc_ipv6_default
USEMODULE += gcoap
# Additional networking modules that can be dropped if not needed
USEMODULE += gnrc_icmpv6_echo
USEMODULE += gnrc_icmpv6_error

# Specify the mandatory networking modules for IPv6 routing
USEMODULE += gnrc_ipv6_router_default

# Required by gcoap example
USEMODULE += od
USEMODULE += fmt

# we want to use SAUL:
USEMODULE += saul_default
# include the shell:
USEMODULE += shell
USEMODULE += shell_commands
# additional modules for debugging:
USEMODULE += ps

# Module for registering to Resource Directory (RD) 
USEMODULE += cord_ep

# needed so that the board can be reached
USEMODULE += netstats_l2
#
# Include tinycbor for data representation
USEPKG += tinycbor
INCLUDE += $(RIOTPKG)/tinycbor/cbor.h

CFLAGS += -DGNRC_IPV6_NIB_CONF_SLAAC=1

# For debugging and demonstration purposes the lifetime is limited to 30s
CFLAGS += -DCORD_LT=30
