.PHONY: all

all: milestone-2-presentation.html milestone-3-presentation.html

milestone-2-presentation.html: milestone-2-presentation.txt
	pandoc -t slidy -s milestone-2-presentation.txt -o milestone-2-presentation.html

milestone-3-presentation.html: milestone-3-presentation.txt
	pandoc -t slidy -s milestone-3-presentation.txt -o milestone-3-presentation.html
